# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7edaf34fd665fbdc8ea109a0252311ae759728399d86648eed28a4250bdfea709f51d7731a1d7f4a3382b9f263d5089e458dd7d0fef8dfafc2057e492c0b7c2a

test:
  secret_key_base: e34e8674ccc27cdb064dd3d19a7e0d9e2b7b2fe5b23e09c5635685934dd68fa5adcf7bc14995b12b3311d3745b6bf3929db4a831c0f88d6e0ddfdf3df330bc51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
